#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers.
        dpkg-trigger update-workbench

        # Initialize configuration database.
        omv-confdbadm create "conf.service.kvm"
        if [ -n "$2" ]; then
          omv-confdbadm migrate "conf.service.kvm" "${2}"
        fi

        # run salt to apply configuration
        omv-salt deploy run kvm

        # Restart monitoring daemon to pick up any updated files
        systemctl try-restart omv-kvm-monitor || :
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
